spring:
  application:
    name: CrazyKid's QQRobot Backend
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbName?characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&useSSL=false&allowMultiQueries=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  main:
    banner-mode: off

maimaiGuessSong:
  enable: true # 启用maimai猜歌小游戏

arcadeCardCounter:
  enable: true # 启用排卡功能

group:
  recall:
    mute: false # 群友撤回是否禁言
